Fix EN + 4SCN AWS deployment
klaytn/klaytn-terraform pull request #3
Opened 2022-03-18 03:14 UTC by iv0rish

- Update EN node using Cypress EN AMI to reduce chaindata migration time.
- Update node's security group : communicate via public IP between nodes.
- Fix typos in directory name

@klaytn/gx_devops I will update CODEOWNERS, apologize for unnecessary notifications.

2022-03-21 22:34 UTC, 2dvorak commented
@iv0rish Would it be possible to add an option for which AMI to use for EN (Cypress or Baobab)?

2022-03-22 00:25 UTC, 2dvorak commented
@iv0rish In case the user wants to create more than 1 EN, we should add index to EN name, too.
https://github.com/iv0rish/klaytn-terraform/blob/phase1-deploy-4scn/service-chain-aws/deploy-4scn/en_node.tf#L25

2022-03-22 01:06 UTC, iv0rish commented
> @iv0rish Would it be possible to add an option for which AMI to use for EN (Cypress or Baobab)?

Yes it is possible. BTW, we should build a clean EN AMI(either Cypress or Baobab) that does not include any node information like node key. I will look into a new AMI pipeline and share you.

2022-03-22 01:08 UTC, iv0rish commented
> @iv0rish In case the user wants to create more than 1 EN, we should add index to EN name, too. https://github.com/iv0rish/klaytn-terraform/blob/phase1-deploy-4scn/service-chain-aws/deploy-4scn/en_node.tf#L25

Added index at [576d813](https://github.com/klaytn/klaytn-terraform/pull/3/commits/576d813603b49c65dcb1605acc609836e75d40a3)

2022-03-23 06:46 UTC, 2dvorak requested changes

2022-03-23 06:46 UTC, 2dvorak commented on serivce-chain-aws/terraform.tfvars
> -# name           = ""   # Name of every resource's name tag
@iv0rish Isn't `terraform.tfvars` still useful for the users to customize to their needs?

2022-03-23 06:46 UTC, 2dvorak commented on service-chain-aws/deploy-4scn/output.tf
> +  description = "SCN instance nodes' private ip. It might help create inventory file when it comes to use ansible"
```suggestion
  description = "SCN instance nodes' public ip. It might help create inventory file when it comes to use ansible"
```

2022-03-23 06:46 UTC, 2dvorak commented on service-chain-aws/deploy-4scn/output.tf
> +  description = "EN instance nodes' private ip. It might help create inventory file when it comes to use ansible"
```suggestion
  description = "EN instance nodes' public ip. It might help create inventory file when it comes to use ansible"
```

2022-03-23 06:48 UTC, 2dvorak commented
@iv0rish Sorry for the late review.. I realized that I didn't submit my review so my comments were pending.

2022-03-28 05:45 UTC, 2dvorak commented on service-chain-aws/deploy-4scn/scn_node.tf
> +
```suggestion
resource "aws_security_group_rule" "ingress_network_rpc" {
  security_group_id = aws_security_group.common.id
  type              = "ingress"
  from_port         = 8551
  to_port           = 8551
  protocol          = "tcp"
  cidr_blocks       = var.ssh_client_ips
}
```

@iv0rish I think we need to allow inbound connection for the RPC port.

2022-03-31 04:47 UTC, iv0rish commented on serivce-chain-aws/terraform.tfvars
> -# name           = ""   # Name of every resource's name tag
@2dvorak I made directory for each phase and move files, it seems deleted but actually they are in the directory.

2022-03-31 07:20 UTC, 2dvorak commented on serivce-chain-aws/terraform.tfvars
> -# name           = ""   # Name of every resource's name tag
@iv0rish I can see other files moved into new directory, but `terraform.tfvars` is deleted and does not appear in the new directory (`deploy_4scn`). Please take a look and add `terraform.tfvars`.

2022-03-31 07:30 UTC, iv0rish commented on serivce-chain-aws/terraform.tfvars
> -# name           = ""   # Name of every resource's name tag
@2dvorak Gotcha! Thanks.

2022-03-31 07:31 UTC, 2dvorak submitted a review, later dismissed

2022-04-06 05:28 UTC, henry-will submitted a review, later dismissed
LGTM

2022-04-07 08:15 UTC, 2dvorak approved these changes
LGTM

2022-04-12 06:06 UTC, henry-will approved these changes

2022-04-12 06:11 UTC, henry-will commented
@jaydenhur @markyim-krust please review this pr for submodule of [servicechain-deploy](https://github.com/klaytn/servicechain-deploy.git) repository

2022-04-21 03:03 UTC, merged